[package]
name = "spst"
version = "0.1.0"
authors = ["Yasufumi Nakamoto <nakamo326@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=3.0.0-beta.2"
rand = "0.8.3"
termion = "1.5.6"
